### ISSUE TITLE
please i cant update its urgent

### ISSUE THREAD

**Issue by uniquechukwuma** [guncebektas/lenkorm#1]
if i write it i will see the query yet its not updating and will show congrat as if it update
$product_name1 = $_POST['product_name'];
        $product_price1 = $_POST['product_price'];
        $product_school1 = $_POST['school'];
        $product_category1 = $_POST['product_category'];
        $product_comment1 = $_POST['product_comment'];
        echo $product_num;
    $updating = update('campus_market_product')->values(array('product_name' => $_POST['product_name'],
                                         'product_price' => $product_price1,
                                         'school' => $product_school1,
                                         'product_category' => $product_category1,
                                         'comment' => $product_comment1))->where('product_id = "$product_num"');

**Comment by guncebektas** [comment]
hi @uniquechukwuma sorry for the delay 
please try

``` php
$updating = update('campus_market_product')->values(array(
    'product_name' => $_POST['product_name'],
    'product_price' => $product_price1,
    'school' => $product_school1,
    'product_category' => $product_category1,
    'comment' => $product_comment1))->where('product_id = '.$product_num);
```

**Comment by uniquechukwuma** [comment]
thanks so so much @guncebektas  i appreciate. hope i can follow you on whatssap? twitter, facebook?

**Comment by uniquechukwuma** [comment]
is there anywhere i could be following personal like whatssap? facebook? email? @guncebektas

**Comment by guncebektas** [comment]
Twitter will be the best option, i generally share my codes in there http://twitter.com/guncebektas @uniquechukwuma .
