### ISSUE TITLE
Please is there anyway i can perform pagination using your class?

### ISSUE THREAD

**Issue by uniquechukwuma** [guncebektas/lenkorm#2]
just help me am stucked because the pagination class i am using requires me to open another connection and make another select statement without your class thanks

$user = find('campus_market_users',$user_id);
$count=0;
//select all the product you upload
$product_result = select('campus_market_product')->where("user_id = '$user_id'")->order('product_id DESC')->limit(10)->results();
foreach($product_result as $key=>$value)
{
    $product_id[] = $product_result[$key]['product_id'];
    $product_name[] = $product_result[$key]['product_name'];
    $product_category[] = $product_result[$key]['product_category'];
    $product_price[] = $product_result[$key]['product_price'];
    $product_date[] = $product_result[$key]['date'];
    $count++;
}

any means to use the class to perform pagination

**Comment by guncebektas** [comment]
@uniquechukwuma try to use limit like 

``` php
->limit('10, 20') 
```

**Comment by uniquechukwuma** [comment]
@guncebektas then how will i get the numrow thats the total number of row in my table

$numrows= select('campus_market_product')->order('product_id DESC');
$num = $numrows->rowCount();
or
$numrows= select('campus_market_product')->order('product_id DESC')->num_rows();

none of them worked

**Comment by uniquechukwuma** [comment]
$numrows= select('campus_market_product')->order('product_id DESC');
$num = $numrows->rowCount();
or 
$numrows= select('campus_market_product')->order('product_id DESC')->num_rows();

none of them worked

**Comment by uniquechukwuma** [comment]
@guncebektas 
1. please how can i use PS to echo as Json please 
2. i can insert the current date and time its shows me 0000.00.00 see code
        $values = array('product_id' => '',
                'product_name' => $p_name,
                'school' => $p_school,
                'phone'=>$p_phone,
                'product_price'=>$p_price,
                'product_category'=>$p_category,
                'product_picture'=>$p_picture,
                'comment'=>$p_description,
                'verified'=>'',
                'trending'=>'',
                'user_id'=>$user_id,
                'pushup'=>'',
                'remove'=>'',
                'date'=>"now()",
                    );

```
    if(insert('campus_market_product')->values($values))
                {
                    echo "congrat";

                }
```

**Comment by guncebektas** [comment]
@uniquechukwuma  there wasn't such function but i added please download new file :)

``` php
/** Number of rows
     *
     * @example select('users')->num_rows();
     * @return integer
     */
    final public function num_rows()
    {
        $query = $this->run(true);
        return $query->num_rows();
        $results = $query->fetch_array();
        return count($results);
    }
```

**Comment by uniquechukwuma** [comment]
@guncebektas  thanks i saw your update. sorry if i worry a lot just needed some few things in order to continue with the class
1. please how can i use PS to echo as Json please 

then 
1. i can insert the current date and time its shows me 0000.00.00 see code the now() sql function did not work
   $values = array('product_id' => '',
   'product_name' => $p_name,
   'school' => $p_school,
   'phone'=>$p_phone,
   'product_price'=>$p_price,
   'product_category'=>$p_category,
   'product_picture'=>$p_picture,
   'comment'=>$p_description,
   'verified'=>'',
   'trending'=>'',
   'user_id'=>$user_id,
   'pushup'=>'',
   'remove'=>'',
   'date'=>"now()",
   );
   
   if(insert('campus_market_product')->values($values))
               {
                   echo "congrat";
   
   ```
           }
   ```
   
   i needed them to continue with my work

**Comment by guncebektas** [comment]
can u please separate your issues?

**Comment by uniquechukwuma** [comment]
okay i will thanks
