### ISSUE TITLE
how do i use mysql date time (now)

### ISSUE THREAD

**Issue by uniquechukwuma** [guncebektas/lenkorm#4]
i can insert the current date and time its shows me 0000.00.00 see code
$values = array('product_id' => '',
'product_name' => $p_name,
'school' => $p_school,
'phone'=>$p_phone,
'product_price'=>$p_price,
'product_category'=>$p_category,
'product_picture'=>$p_picture,
'comment'=>$p_description,
'verified'=>'',
'trending'=>'',
'user_id'=>$user_id,
'pushup'=>'',
'remove'=>'',
'date'=>"now()",
);

```
if(insert('campus_market_product')->values($values))
            {
                echo "congrat";

            }
```

**Comment by guncebektas** [comment]
use now() like that @uniquechukwuma 

``` php
$values = array('product_id' => '',
'product_name' => $p_name,
'school' => $p_school,
'phone'=>$p_phone,
'product_price'=>$p_price,
'product_category'=>$p_category,
'product_picture'=>$p_picture,
'comment'=>$p_description,
'verified'=>'',
'trending'=>'',
'user_id'=>$user_id,
'pushup'=>'',
'remove'=>'',
'date'=>now(),
);
```
